apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: internal-launchrock-test-test-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: internal-launchrock-test-test-api
    spec:
      containers:
        - name: internal-launchrock-test-test-api
          image: 569325332953.dkr.ecr.us-east-1.amazonaws.com/internal-launchrock-test-test-api:__TAG__
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: internal-launchrock-test-test-api-secrets
            - configMapRef:
                name: internal-launchrock-test-test-api-configmap
          ports:
            - containerPort: 3000
